"use client";

import { CheckCircle2,ShieldCheck,X } from "lucide-react";
import { useState,type FormEvent } from "react";
import { uploadSecureImage } from "../lib/media-upload";
import { ImageDraftPicker } from "./ImageDraftPicker";

type Props={open:boolean;onClose:()=>void};
type Category="official"|"faculties"|"clubs"|"scholarship"|"events";
const defaultDates=()=>{const start=new Date();const expiry=new Date(Date.now()+30*24*60*60*1000);const local=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60_000).toISOString().slice(0,16);return{startsAt:local(start),expiresAt:local(expiry)};};

export function AnnouncementSubmissionDialog({open,onClose}:Props){
  const dates=defaultDates();const [draft,setDraft]=useState({title:"",summary:"",category:"clubs" as Category,...dates});const [image,setImage]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");
  if(!open)return null;
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/network/announcements",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...draft,startsAt:new Date(draft.startsAt).toISOString(),expiresAt:new Date(draft.expiresAt).toISOString()})});const payload=await response.json() as {data?:{id:string};error?:{message?:string}};if(!response.ok||!payload.data)throw new Error(payload.error?.message??"Elan göndərilmədi.");let warning="";if(image)try{await uploadSecureImage(image,"announcement",payload.data.id);}catch(uploadError){warning=` Şəkil yüklənmədi: ${uploadError instanceof Error?uploadError.message:"yükləmə xətası"}`;}setImage(null);setSuccess(`Elan admin yoxlanışına göndərildi.${warning}`);}catch(caught){setError(caught instanceof Error?caught.message:"Elan göndərilmədi.");}finally{setBusy(false);}}
  return <div className="content-submission-backdrop" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget&&!busy)onClose();}}><section className="content-submission-dialog" role="dialog" aria-modal="true" aria-labelledby="announcement-submission-title"><header><div><small>İCMA ELANI</small><h2 id="announcement-submission-title">Elan göndər</h2></div><button type="button" onClick={onClose} disabled={busy} aria-label="Bağla"><X size={19}/></button></header>{success?<div className="content-submission-success"><CheckCircle2 size={36}/><h3>Yoxlanışa göndərildi</h3><p>{success}</p><button type="button" onClick={onClose}>Bağla</button></div>:<form onSubmit={submit}><div className="content-submission-note"><ShieldCheck size={18}/><p>Elan yalnız admin yoxladıqdan sonra platformada görünəcək. Mənbə kimi profil adın göstəriləcək.</p></div><ImageDraftPicker file={image} onChange={setImage} label="Elan şəkli (istəyə bağlı)"/><div className="content-submission-grid"><label className="is-wide"><span>Başlıq</span><input value={draft.title} onChange={(e)=>setDraft({...draft,title:e.target.value})} minLength={3} maxLength={180} required autoFocus/></label><label><span>Kateqoriya</span><select value={draft.category} onChange={(e)=>setDraft({...draft,category:e.target.value as Category})}><option value="official">Rəsmi</option><option value="faculties">Fakültə</option><option value="clubs">Klub</option><option value="scholarship">Təqaüd</option><option value="events">Tədbir</option></select></label><label><span>Yayım başlanğıcı</span><input type="datetime-local" value={draft.startsAt} onChange={(e)=>setDraft({...draft,startsAt:e.target.value})} required/></label><label className="is-wide"><span>Elanın mətni</span><textarea value={draft.summary} onChange={(e)=>setDraft({...draft,summary:e.target.value})} minLength={10} maxLength={800} rows={5} required/></label><label className="is-wide"><span>Bitmə vaxtı</span><input type="datetime-local" value={draft.expiresAt} onChange={(e)=>setDraft({...draft,expiresAt:e.target.value})} required/></label></div>{error?<p className="content-submission-error" role="alert">{error}</p>:null}<footer><button type="button" onClick={onClose} disabled={busy}>Ləğv et</button><button type="submit" disabled={busy}>{busy?"Göndərilir…":"Admin yoxlanışına göndər"}</button></footer></form>}</section></div>;
}
